name: CI

on:
  push:
    branches: [main]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_and_lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Read the pnpm version from the `.pnpmrc` file
      - name: Read .pnpmrc
        id: pnpm_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.pnpmrc

      - name: Cache PNPM modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.0
        with:
          version: '${{ steps.pnpm_version.outputs.content }}'

      # Read node version from `.nvmrc` file
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - uses: actions/setup-node@v3
        with:
          # use the output from the action
          node-version: '${{ steps.nvmrc.outputs.node_version }}'

      - name: Install `node_modules`
        run: pnpm install

      - name: Tests
        run: pnpm run test

      - name: Linting
        run: pnpm run lint

      - name: Prettier
        run: pnpm run prettier:check
